version: '3.8'

services:
  agent-b-recreation:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - statedge-network

networks:
  statedge-network:
    external: true